const KEY='cqepro-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{project:{name:'Sample Residential Project',client:'',contractor:'',location:'',engineer:'',ref:'',date:new Date().toISOString().slice(0,10)},rates:[{code:'EXC',desc:'Earth excavation',cat:'Earthwork',unit:'m³',mat:0,lab:450,mach:120,oh:5,profit:10,gst:18},{code:'PCC',desc:'PCC 1:4:8',cat:'Concrete',unit:'m³',mat:4200,lab:900,mach:250,oh:5,profit:10,gst:18},{code:'RCC20',desc:'RCC M20',cat:'Concrete',unit:'m³',mat:5500,lab:1200,mach:300,oh:5,profit:10,gst:18},{code:'RCC25',desc:'RCC M25',cat:'Concrete',unit:'m³',mat:5800,lab:1200,mach:300,oh:5,profit:10,gst:18},{code:'STEEL',desc:'Reinforcement steel',cat:'Steel',unit:'kg',mat:72,lab:12,mach:2,oh:5,profit:10,gst:18},{code:'BRICK',desc:'Brick masonry',cat:'Masonry',unit:'m³',mat:4200,lab:1200,mach:0,oh:5,profit:10,gst:18},{code:'BLOCK',desc:'Block masonry',cat:'Masonry',unit:'m³',mat:3600,lab:1100,mach:0,oh:5,profit:10,gst:18},{code:'PLIN',desc:'Internal plaster 12mm',cat:'Plaster',unit:'m²',mat:85,lab:90,mach:0,oh:5,profit:10,gst:18},{code:'PLEX',desc:'External plaster 15mm',cat:'Plaster',unit:'m²',mat:100,lab:105,mach:0,oh:5,profit:10,gst:18},{code:'FLOOR',desc:'Tile flooring',cat:'Flooring',unit:'m²',mat:650,lab:180,mach:0,oh:5,profit:10,gst:18},{code:'PAINT',desc:'Internal painting',cat:'Painting',unit:'m²',mat:65,lab:55,mach:0,oh:5,profit:10,gst:18},{code:'WPROOF',desc:'Waterproofing',cat:'Waterproofing',unit:'m²',mat:180,lab:100,mach:0,oh:5,profit:10,gst:18},{code:'ROOF',desc:'Roofing sheet work',cat:'Roofing',unit:'m²',mat:850,lab:220,mach:0,oh:5,profit:10,gst:18}],boq:[],materials:[],steel:[],plumbing:[],electrical:[]};
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function rate(r){let basic=+r.mat+ +r.lab+ +r.mach; let oh=basic*(+r.oh||0)/100; let profit=(basic+oh)*(+r.profit||0)/100; return basic+oh+profit;}
function totals(){let mat=0,lab=0,mach=0,total=0; state.boq.forEach(x=>{let r=state.rates.find(a=>a.code===x.code);if(!r)return;let q=+x.qty||0;mat+=q*r.mat;lab+=q*r.lab;mach+=q*r.mach;total+=q*rate(r)});return{mat,lab,mach,total,items:state.boq.length};}
function money(n){return '₹'+(+n||0).toLocaleString('en-IN',{maximumFractionDigits:2});}
function calcQty(){let l=+document.querySelector('#ql').value||0,w=+document.querySelector('#qw').value||0,h=+document.querySelector('#qh').value||0,n=+document.querySelector('#qn').value||1,t=+document.querySelector('#qt').value||1,d=+document.querySelector('#qd').value||0,wp=+document.querySelector('#qwp').value||0;let base=l*w*(h||t)*n;let q=base*(1-d/100)*(1+wp/100);let unit=document.querySelector('#qu').value;return{q,base,unit};}
function page(title,body){return `<div class="page"><div class="pagehead"><h2>${title}</h2></div>${body}</div>`}
function render(){let t=totals();let app=document.querySelector('#app');let p=state.page||'dashboard';let body='';
if(p==='dashboard') body=page('Dashboard',`<div class="cards"><div><small>Total Project Cost</small><b>${money(t.total)}</b></div><div><small>Material Cost</small><b>${money(t.mat)}</b></div><div><small>Labour Cost</small><b>${money(t.lab)}</b></div><div><small>Machinery</small><b>${money(t.mach)}</b></div><div><small>BOQ Items</small><b>${t.items}</b></div></div><div class="panel"><h3>Project</h3><div class="grid">${field('Project name','pname',state.project.name)}${field('Client','pclient',state.project.client)}${field('Contractor','pcontractor',state.project.contractor)}${field('Location','plocation',state.project.location)}${field('Engineer / Estimator','pengineer',state.project.engineer)}${field('Reference','pref',state.project.ref)}</div><button onclick="saveProject()">Save Project</button></div><div class="quick">${['Quantity Calculator','BOQ','Rate Master','Rate Analysis','Materials','Steel','Plumbing','Electrical','Reports'].map(x=>`<button onclick="go('${x.toLowerCase().replaceAll(' ','')}')">${x}</button>`).join('')}</div>`);
else if(p==='quantitycalculator') body=page('Civil Quantity Calculator',`<div class="panel"><div class="grid">${field('Length','ql','10','number')}${field('Width','qw','0.30','number')}${field('Height / Depth','qh','0.50','number')}${field('Number','qn','4','number')}${field('Thickness','qt','0.12','number')}${field('Deduction %','qd','0','number')}${field('Waste %','qwp','0','number')}<label>Unit<select id="qu"><option>m³</option><option>m²</option><option>m</option><option>ft³</option><option>ft²</option></select></label></div><button onclick="doCalc()">Calculate</button><div id="qresult" class="result">10 × 0.30 × 0.50 × 4 = 6.00 m³</div></div><div class="panel"><h3>Material requirement — concrete</h3><p>Typical nominal mix quantities can be edited in the calculator. For 1 m³ concrete, use project/specification-approved mix proportions.</p><div class="grid"><label>Cement bags / m³<input id="cementpm" type="number" value="8"></label><label>Fine aggregate m³ / m³<input id="sandpm" type="number" value="0.42"></label><label>Coarse aggregate m³ / m³<input id="aggpm" type="number" value="0.84"></label></div><button onclick="materialCalc()">Calculate Materials</button><div id="mresult" class="result"></div></div>`);
else if(p==='boq') body=page('BOQ',`<div class="toolbar"><button onclick="addBoq()">+ Add Item</button><button onclick="exportCSV()">Export CSV</button></div><div class="tablewrap"><table><thead><tr><th>Sl</th><th>Code</th><th>Description</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th><th></th></tr></thead><tbody>${state.boq.map((x,i)=>{let r=state.rates.find(a=>a.code===x.code);let rr=r?rate(r):0;return `<tr><td>${i+1}</td><td>${esc(x.code)}</td><td>${esc(r?.desc||x.desc)}</td><td><input value="${x.qty}" onchange="editBoq(${i},this.value)"></td><td>${esc(r?.unit||x.unit||'')}</td><td>${money(rr)}</td><td>${money(rr*(+x.qty||0))}</td><td><button class="danger" onclick="delBoq(${i})">Delete</button></td></tr>`}).join('')}</tbody></table></div><div class="total">Grand Total: ${money(t.total)}</div>`);
else if(p==='ratemaster') body=page('Editable Rate Master',`<div class="toolbar"><button onclick="addRate()">+ Add Rate</button><button onclick="exportRates()">Export Rates</button></div><div class="tablewrap"><table><thead><tr><th>Code</th><th>Description</th><th>Category</th><th>Unit</th><th>Material</th><th>Labour</th><th>Machinery</th><th>OH%</th><th>Profit%</th><th>GST%</th><th>Final Rate</th><th></th></tr></thead><tbody>${state.rates.map((r,i)=>`<tr><td>${esc(r.code)}</td><td>${esc(r.desc)}</td><td>${esc(r.cat)}</td><td>${esc(r.unit)}</td><td><input type="number" value="${r.mat}" onchange="editRate(${i},'mat',this.value)"></td><td><input type="number" value="${r.lab}" onchange="editRate(${i},'lab',this.value)"></td><td><input type="number" value="${r.mach}" onchange="editRate(${i},'mach',this.value)"></td><td><input type="number" value="${r.oh}" onchange="editRate(${i},'oh',this.value)"></td><td><input type="number" value="${r.profit}" onchange="editRate(${i},'profit',this.value)"></td><td>${r.gst}</td><td>${money(rate(r))}</td><td><button class="danger" onclick="delRate(${i})">Delete</button></td></tr>`).join('')}</tbody></table></div>`);
else if(p==='rateanalysis') body=page('Rate Analysis',`<div class="panel"><label>Item<select id="raitem">${state.rates.map(r=>`<option value="${r.code}">${esc(r.code)} — ${esc(r.desc)}</option>`).join('')}</select></label><button onclick="showRA()">Analyze</button><div id="raresult"></div></div>`);
else if(p==='materials') body=page('Material Analysis',`<div class="panel"><p>Project material summary from BOQ rates.</p><table><tr><th>Material</th><th>Estimated requirement</th><th>Note</th></tr><tr><td>Cement</td><td>Derived from concrete/masonry/plaster mix settings</td><td>Use approved mix design</td></tr><tr><td>Fine aggregate</td><td>Derived from mix</td><td>m³</td></tr><tr><td>Coarse aggregate</td><td>Derived from mix</td><td>m³</td></tr><tr><td>Steel</td><td>${money(t.mat?0:0)} placeholder until BBS quantities are entered</td><td>kg/tonne</td></tr></table></div>`);
else if(p==='steel') body=page('Steel / BBS Calculator',`<div class="panel"><div class="grid">${field('Bar diameter (mm)','sd','12','number')}${field('Number of bars','sn','10','number')}${field('Bar length (m)','sl','6','number')}${field('Lap length (m)','slap','0','number')}${field('Bend allowance (m)','sba','0','number')}</div><button onclick="steelCalc()">Calculate</button><div id="sresult" class="result"></div></div><div class="panel"><h3>Unit weight formula</h3><p>Unit weight = d² / 162 kg/m. Total weight = total length × unit weight.</p></div>`);
else if(p==='plumbing') body=page('Plumbing Details',`<div class="panel"><div class="grid">${field('Item','plitem','Water supply pipe')}${field('Quantity','plqty','1','number')}${field('Unit','plunit','m')}${field('Rate ₹','plrate','0','number')}</div><button onclick="addService('plumbing')">Add Plumbing Item</button></div><table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th><th></th></tr></thead><tbody>${state.plumbing.map((x,i)=>`<tr><td>${esc(x.item)}</td><td>${x.qty}</td><td>${esc(x.unit)}</td><td>${money(x.rate)}</td><td>${money(x.qty*x.rate)}</td><td><button class="danger" onclick="delService('plumbing',${i})">Delete</button></td></tr>`).join('')}</tbody></table>`);
else if(p==='electrical') body=page('Electrical Details',`<div class="panel"><div class="grid">${field('Item','elitem','Light point')}${field('Quantity','elqty','1','number')}${field('Unit','elunit','no')}${field('Rate ₹','elrate','0','number')}</div><button onclick="addService('electrical')">Add Electrical Item</button></div><table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th><th></th></tr></thead><tbody>${state.electrical.map((x,i)=>`<tr><td>${esc(x.item)}</td><td>${x.qty}</td><td>${esc(x.unit)}</td><td>${money(x.rate)}</td><td>${money(x.qty*x.rate)}</td><td><button class="danger" onclick="delService('electrical',${i})">Delete</button></td></tr>`).join('')}</tbody></table>`);
else if(p==='reports') body=page('Reports & Cost Summary',`<div class="cards"><div><small>Material</small><b>${money(t.mat)}</b></div><div><small>Labour</small><b>${money(t.lab)}</b></div><div><small>Machinery</small><b>${money(t.mach)}</b></div><div><small>Estimated Total</small><b>${money(t.total)}</b></div></div><div class="panel"><button onclick="window.print()">Print / Save PDF</button><button onclick="exportCSV()">Export BOQ CSV</button></div>`);
app.innerHTML=`<aside class="side"><h1>Civil Estimate Pro</h1>${[['dashboard','Dashboard'],['quantitycalculator','Quantity Calculator'],['boq','BOQ'],['ratemaster','Rate Master'],['rateanalysis','Rate Analysis'],['materials','Materials'],['steel','Steel / BBS'],['plumbing','Plumbing'],['electrical','Electrical'],['reports','Reports']].map(a=>`<button class="nav ${p===a[0]?'active':''}" onclick="go('${a[0]}')">${a[1]}</button>`).join('')}<div class="sidebottom"><button onclick="backup()">Backup</button><button onclick="restore()">Restore</button></div></aside><main>${body}</main>`;}
function field(label,id,val='',type='text'){return `<label>${label}<input id="${id}" type="${type}" value="${esc(val)}"></label>`}
function go(p){state.page=p;save()}
function saveProject(){Object.assign(state.project,{name:document.querySelector('#pname').value,client:document.querySelector('#pclient').value,contractor:document.querySelector('#pcontractor').value,location:document.querySelector('#plocation').value,engineer:document.querySelector('#pengineer').value,ref:document.querySelector('#pref').value});save();alert('Project saved locally.');}
function addBoq(){let code=prompt('Enter rate code (e.g. RCC25)');if(!code||!state.rates.some(r=>r.code===code))return alert('Rate code not found. Add it in Rate Master first.');let qty=prompt('Quantity', '1');state.boq.push({code,qty:+qty||0});save()}
function editBoq(i,v){state.boq[i].qty=Math.max(0,+v||0);save()}
function delBoq(i){if(confirm('Delete this BOQ item?')){state.boq.splice(i,1);save()}}
function addRate(){let code=prompt('Item code');if(!code)return;state.rates.push({code,desc:prompt('Description')||'',cat:prompt('Category')||'Other',unit:prompt('Unit')||'m³',mat:0,lab:0,mach:0,oh:5,profit:10,gst:18});save()}
function editRate(i,k,v){state.rates[i][k]=Math.max(0,+v||0);save()}
function delRate(i){if(confirm('Delete rate? Existing BOQ items using it will no longer have a rate.')){state.rates.splice(i,1);save()}}
function doCalc(){let x=calcQty();document.querySelector('#qresult').innerHTML=`<b>Calculation:</b> Base = ${x.base.toFixed(3)}; Net quantity = <b>${x.q.toFixed(3)} ${x.unit}</b>`}
function materialCalc(){let q=calcQty().q, c=+document.querySelector('#cementpm').value||0,s=+document.querySelector('#sandpm').value||0,a=+document.querySelector('#aggpm').value||0;document.querySelector('#mresult').innerHTML=`For ${q.toFixed(3)} m³: Cement <b>${(q*c).toFixed(2)} bags</b>, Fine aggregate <b>${(q*s).toFixed(3)} m³</b>, Coarse aggregate <b>${(q*a).toFixed(3)} m³</b>.`}
function steelCalc(){let d=+document.querySelector('#sd').value||0,n=+document.querySelector('#sn').value||0,l=+document.querySelector('#sl').value||0,lap=+document.querySelector('#slap').value||0,ba=+document.querySelector('#sba').value||0,total=n*(l+lap+ba),uw=d*d/162;document.querySelector('#sresult').innerHTML=`Total length: <b>${total.toFixed(2)} m</b><br>Unit weight: <b>${uw.toFixed(3)} kg/m</b><br>Total steel: <b>${(total*uw).toFixed(2)} kg</b> (${(total*uw/1000).toFixed(3)} tonne)`}
function showRA(){let r=state.rates.find(x=>x.code===document.querySelector('#raitem').value);if(!r)return;let basic=r.mat+r.lab+r.mach,oh=basic*r.oh/100,pr=(basic+oh)*r.profit/100,gst=(basic+oh+pr)*r.gst/100;document.querySelector('#raresult').innerHTML=`<div class="result">Material ${money(r.mat)} + Labour ${money(r.lab)} + Machinery ${money(r.mach)} = <b>Basic ${money(basic)}</b><br>Overhead ${money(oh)} → Profit ${money(pr)} → GST ${money(gst)}<br><b>Final Rate ${money(basic+oh+pr+gst)} / ${r.unit}</b></div>`}
function addService(kind){let pre=kind==='plumbing'?'pl':'el';let x={item:document.querySelector('#'+pre+'item').value,qty:+document.querySelector('#'+pre+'qty').value||0,unit:document.querySelector('#'+pre+'unit').value,rate:+document.querySelector('#'+pre+'rate').value||0};state[kind].push(x);save()}
function delService(k,i){state[k].splice(i,1);save()}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')}
function download(name,text,type='text/csv'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCSV(){download('BOQ.csv',csv([['Sl','Code','Description','Quantity','Unit','Rate','Amount'],...state.boq.map((x,i)=>{let r=state.rates.find(a=>a.code===x.code),rr=r?rate(r):0;return [i+1,x.code,r?.desc||'',x.qty,r?.unit||'',rr,rr*x.qty]} )]))}
function exportRates(){download('RateMaster.csv',csv([['Code','Description','Category','Unit','Material','Labour','Machinery','OH%','Profit%','GST%','Final'],...state.rates.map(r=>[r.code,r.desc,r.cat,r.unit,r.mat,r.lab,r.mach,r.oh,r.profit,r.gst,rate(r)])]))}
function backup(){download('CivilEstimateBackup.json',JSON.stringify(state,null,2),'application/json')}
function restore(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{let f=i.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{Object.assign(state,JSON.parse(rd.result));save();alert('Backup restored.')}catch(e){alert('Invalid backup file')}};rd.readAsText(f)};i.click()}
render();